version: '3.8'
services:
  tomato-app:
    image: tomato-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/app
